obstacle_range: 2.5
raytrace_range: 3.0
robot_radius: 0.3
inflation_radius: 0.1
max_obstacle_height: 2.0
min_obstacle_height: 0.0
observation_sources: laser_scan_sensor



laser_scan_sensor: {sensor_frame: laser_frame, data_type: LaserScan, topic: filtered_scan, marking: true, clearing: true}
